services:
  - type: web
    name: yaksok-jobja
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: yaksok-db
          property: jdbcUrl
      - key: DB_USERNAME
        fromDatabase:
          name: yaksok-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: yaksok-db
          property: password

databases:
  - name: yaksok-db
    plan: free
    databaseName: yaksok
