services:
  - type: web
    name: yaksok-jobja
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

databases:
  - name: yaksok-db
    plan: free
    region: singapore
    databaseName: yaksok
