/* ============================================
   일정 투표 시스템 - MSSQL 데이터베이스 스크립트
   ============================================ */

/* 사용자 테이블 */
CREATE TABLE [USER] (
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL /* 암호화된 비밀번호 */,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

/* 일정 테이블 */
CREATE TABLE SCHEDULE (
    SCHEDULE_ID INT PRIMARY KEY IDENTITY(1,1),
    TITLE NVARCHAR(100) NOT NULL /* 일정 제목 (합주, 모임 등) */,
    ADMIN_ID INT NOT NULL FOREIGN KEY REFERENCES [USER](USER_ID),
    SHARE_CODE NVARCHAR(20) NOT NULL UNIQUE /* 초대 링크 코드 */,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

/* 일정 후보 날짜 테이블 */
CREATE TABLE SCHEDULE_DATE (
    DATE_ID INT PRIMARY KEY IDENTITY(1,1),
    SCHEDULE_ID INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE,
    CANDIDATE_DATE DATE NOT NULL /* 후보 날짜 */,
    CREATED_AT DATETIME DEFAULT GETDATE()
);

/* 사용자 응답 테이블 */
CREATE TABLE USER_RESPONSE (
    RESPONSE_ID INT PRIMARY KEY IDENTITY(1,1),
    DATE_ID INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE_DATE(DATE_ID) ON DELETE CASCADE,
    USER_NAME NVARCHAR(50) NOT NULL /* 익명 또는 실제 이름 */,
    IS_AVAILABLE BIT NOT NULL /* 1: 가능, 0: 불가능 */,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

/* 인덱스 생성 */
CREATE INDEX IDX_SCHEDULE_ADMIN ON SCHEDULE(ADMIN_ID);
CREATE INDEX IDX_SCHEDULE_DATE_SCHEDULE ON SCHEDULE_DATE(SCHEDULE_ID);
CREATE INDEX IDX_USER_RESPONSE_DATE ON USER_RESPONSE(DATE_ID);
CREATE INDEX IDX_SCHEDULE_CODE ON SCHEDULE(SHARE_CODE);
